### ISSUE TITLE
Ongoing issues

### ISSUE THREAD

**Issue by kevinunger** [CryptoBlades/cryptoblades#1399]
1.) Frontend / Ui / Ux (Excluding Plaza, Quests, Treasury, Bridge)
---
1.1 ) General
---
- [ ] 1.1.1) Why are only 4 nav-links on the nav-bar?
![image](https://user-images.githubusercontent.com/5601589/169294835-5c25397c-e794-48b3-bf29-1bf498565239.png)
- [ ] 1.1.2) icon not aligned (baseline)
![image](https://user-images.githubusercontent.com/5601589/169295135-a47f719e-22d5-4dce-9f0e-b8d21ae25bd6.png)
- [ ] 1.1.3) Weird css animation when expanding left bar. (Content list get's squished)
![vite](https://user-images.githubusercontent.com/5601589/169296167-ec299c01-589a-4ceb-9999-35c4d8d57561.gif)
- [ ] 1.1.4)  Still called 'combat' and not 'adventure' here 
![image](https://user-images.githubusercontent.com/5601589/169308528-f4ce2d69-8fdc-40e9-ab55-7864e3b67c84.png)

- 1.2 ) Blacksmith
---
- [ ] 1.2.1) Confusing selection process when on 'salvage' - Last selected element has a golden border
![vite](https://user-images.githubusercontent.com/5601589/169297629-5a9d31b0-8750-4ee4-a7ff-39e8534d75be.gif)
- [ ] 1.2.2) Initially, pagination indicator is not present when loading a large list of weapons; It's there after a couple of seconds
![vite](https://user-images.githubusercontent.com/5601589/169300325-28c5d909-5d62-4e79-9ae8-a32156aa7825.gif)
- [ ] 1.2.3) Text shouldn't say 'durability will be full at ...', if durability is at 100%
![image](https://user-images.githubusercontent.com/5601589/169300660-280046a5-e7dd-401f-94f7-7c9d85f97f07.png)
- [ ] 1.2.4) Forging button should be visibly disabled (it is disabled, just not reflect on the ui), when no element is selected
![image](https://user-images.githubusercontent.com/5601589/169301107-11944c9f-2a18-4261-85b8-e0d7df644586.png)
- [ ] 1.2.5) Forging tooltip (mouse is on hover over the tooltip) is under the forging modal (both tooltips)
![image](https://user-images.githubusercontent.com/5601589/169301332-b771db3c-f5c0-4341-9d27-ff0f30420c40.png)
- [ ] 1.2.6) Why is the 'show reforged' filter gone
- [ ] 1.2.7) Close btn is not functional. Can be removed
![image](https://user-images.githubusercontent.com/5601589/169329730-0db318e3-0481-4a2e-9642-ac2fcff9cdfd.png)

1.3) Raid
---
- [ ] 1.3.1) Raid is not loading, if you have any chars. Atleast a error msg like on /Quests would be nice
- [ ] 1.3.2) The timer shouldn't be negative and counting 'up'. Better just counting down (Like 'next raid in: xx:xx:xx)
![image](https://user-images.githubusercontent.com/5601589/169303866-a9ea75c8-7938-4abc-9c5b-5c4c9b9b3ebb.png)
- [ ] 1.3.3) Old placeholder image for rewarded weapon
![image](https://user-images.githubusercontent.com/5601589/169304186-6e1317a8-a0a2-4ed2-b24c-2c1556508581.png)
- [ ] 1.3.4) Worst bug so far: Why is this jumping up
![vite](https://user-images.githubusercontent.com/5601589/169304391-6f28d002-f759-4916-a4f7-b6b85ded6da3.gif)
- [ ] 1.3.5) The weapon icon should be aligned with the char icon (same size + same font color
![image](https://user-images.githubusercontent.com/5601589/169306392-af186fb5-0688-4314-98d6-9f8e18d91b58.png)
- [ ] 1.3.6) 'Claim Rewards' not visibly disabled when no rewards available
![image](https://user-images.githubusercontent.com/5601589/169305577-20d914c6-917b-4e93-beb8-3239e2c52efb.png)
- [ ] 1.3.7) After a  user selects a char, a weapon and then clicks 'Join Raid' he get's a pop-up that the raid has not yet started. We should just visibly disable the 'Join Raid' Button beforehand, remove the pop-up and add a tooltip on hover over the disabled btn that says 'Raid has not yet started. Please wait xx:xx:xx'; Same when no weapon is selected
- [ ] 1.3.8) Weapons 'stretch'. Too big on small weapon list and left border is cut off
![image](https://user-images.githubusercontent.com/5601589/169307878-bb70d725-d8af-45d0-adee-1155247ef237.png)

1.4) Combat
---
- [ ] 1.4.1) X and Y Overflow on combat
![image](https://user-images.githubusercontent.com/5601589/169311728-43c2fc56-2bdc-49ad-b524-ee5bb7b4f795.png)

2.) Errors
---
2.1) General
- [ ] 2.1.1 Multiple JSON-RPC errors on load
![image](https://user-images.githubusercontent.com/5601589/169314917-a56aa9f4-3506-498b-a988-57e9f3018ad2.png)
These are happening while createStore is executed. Log:
![image](https://user-images.githubusercontent.com/5601589/169318206-0484bd2f-8eba-4708-90c6-1b22fb5d797e.png)
![image](https://user-images.githubusercontent.com/5601589/169318461-139a5d7a-c0e7-4318-851c-56a06660a714.png)
- [ ] 2.1.2 Error when clicking certain items
![image](https://user-images.githubusercontent.com/5601589/169319783-81c22689-778d-4882-8579-f8b1cb73c656.png)

---
2.2) Combat
---
- [ ] 2.2.1) Error message get's displayed for the user after fight. Can't pin that down rn.
The error itself is a problem, but we shouldn't dump that on the frontend as well. 
![image](https://user-images.githubusercontent.com/5601589/169311818-79c638cb-7ce6-4b2f-ace5-903aa012d735.png)
```
Error: Transaction has been reverted by the EVM: { "blockHash": "0x6b04676cca5ced503370106f2f982450809f36ca913f85b9b9ce4780f6fb1a11", "blockNumber": 17938879, "contractAddress": null, "cumulativeGasUsed": 30431788, "from": "0xab47675fdb7ae6e47431bd2d4bd9cd7bac7fde61", "gasUsed": 36495, "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "status": false, "to": "0x39bea96e13453ed52a734b6aceed4c41f57b2271", "transactionHash": "0xc67998603b33e87ada10b4528ff05e30359a561ca3a3718d8b22da9ea852fa1e", "transactionIndex": 393, "type": "0x0", "events": {} }
```
or
```
Error: JsonRpcEngine: Response has no error or result for request: { "method": "eth_call", "params": [ { "from": "0xc2573a26297a0c952c92bb48fdcb6929524f7f48", "data": "0x499eeeeb", "to": "0x39bea96e13453ed52a734b6aceed4c41f57b2271" }, "0x1114d19" ], "jsonrpc": "2.0", "id": 3684186064, "origin": "https://app.cryptoblades.io/", "tabId": 1305 } { "request": { "method": "eth_call", "params": [ { "from": "0xc2573a26297a0c952c92bb48fdcb6929524f7f48", "data": "0x499eeeeb", "to": "0x39bea96e13453ed52a734b6aceed4c41f57b2271" }, "0x1114d19" ], "jsonrpc": "2.0", "id": 3684186064, "origin": "https://app.cryptoblades.io/", "tabId": 1305 } }
```

2.3) Plaza
---
- [ ] 2.3.1) Error on load Plaza:656
![image](https://user-images.githubusercontent.com/5601589/169313777-934ab84b-a005-409b-be21-f97fa5d4716d.png)
```
    async updateMintCharacterFee() {
      ...
      const skillRecruitCost = await this.contracts.CryptoBlades.methods.usdToSkill(recruitCost).call();
      ...
    }
```
(It's called on `created()`. So `contracts` is probably still `undefined`. Needs a check for contracts to exist)

2.4) Leaderboard
- [ ] 2.4.1) Not loading

2.5) Blacksmith
- [ ] 2.5.1) Flow Forging: 
 'Cooling Forge ... ' disappears before transaction went through
![image](https://user-images.githubusercontent.com/5601589/169330050-e6a7345e-9f71-4749-bf41-8f40733a1017.png)
![image](https://user-images.githubusercontent.com/5601589/169330137-57f36cf2-4065-47b1-9348-11f73ccf67da.png)
After transaction is successfull, the loading animation appears.
- [ ] 2.5.2) Not enough funds on 10x forge
![image](https://user-images.githubusercontent.com/5601589/169332291-8d9ec1e6-8b28-45ec-a9bc-61665c3bfe2f.png)
- [ ] 2.5.3) When declining / aborting the transaction for 1x / 10x forge, the forging animation is still triggered
- [ ] 2.5.4) No confirmation on salvage
- [ ] 2.5.5) The dust display on the right is not reset after salvage
![image](https://user-images.githubusercontent.com/5601589/169336678-e73d8ec0-5741-4a86-88cd-436fd0323e08.png)
- [ ] 2.5.6) Weapon list is not updated after salvage

Suggestions, not bugs:
1.) - Bazaar icon text has an icon besides it when in the navbar, but not in the menu on the right ( 'Wiki' should have the same icon, bc it's an external link too)
2.) - Can we exclude the icons shown in the navbar from the right menu?
3.) - The weapons list shows all excluding the ones marked as favorites, when the 'show favorites' filter is disabled and shows all weapons when 'show favorites' filter is enabled
Wouldn't it be more logical if we would show only the favorites when clicking the 'show favorites button' ?
4.) - 'Desposit' and the SKILL Coin Icon do the same thing
![image](https://user-images.githubusercontent.com/5601589/169296721-cc5dc52b-6511-462d-b43c-8b551a8b1cb5.png)
5.) - A Tooltip explaining the raid shortly would be great. 
6.) - Should we remove 'Merchandise' completly?
7.) There is a hardcoded delay for this message:
![image](https://user-images.githubusercontent.com/5601589/169333280-0a364a93-a952-40c3-832c-00dbf08108b6.png)
It's a bit confusing when this flies in seemingly randomly. I'd like to remove the delay or the message entirely.
8.) There should be a 'deselect all' btn when selecting multiple nfts e.g. when salvaging. E.g. if you select multiple swords, change filters, etc. you need to remove all filters and deselect all select by hand again.

**Comment by Sellie96** [comment]
My word Kevin, extensive list. Few of them I have notes on

 1.1.1) Why are only 4 nav-links on the nav-bar?    We are redoing the claim section into that bar, this will lead to it being more full, until that time we are limiting the number shown we can increase it when we know the available space. This covers a few more points too.
 
 1.2.6) They are just always shown now. We can have it back but needs defauting to true, it was annoying explaining to people they aren't missing weapons.
 
 1.3.2) Did raids fall over? This was not the case before
 
 1.3.6) See point 1. Still needs rework
 
 6.) - Should we remove 'Merchandise' completly? Absolutely. Legacy code needs cleaning
 
 May have missed some explainable ones, but generally I agree with most of the others. Good work identifying these

**Comment by poshdan** [comment]
wanted to add, victory chance on raids has been irrelevant since september. It doesn't need to be shown unless we reintroduce it (not until raids v2, if ever)

**Comment by poshdan** [comment]
On the staking page, the default behavior is for the numbers to load as 0.
Could we add a loading circle somewhere (and hide the 0s) so people don't freak out that their tokens/rewards are gone before the rpc responds?

**Comment by kevinunger** [comment]
Ok, added your first point to the issue list!

for the second one: 
You mean adding the token icons on the top and having an arrow here?
![image](https://user-images.githubusercontent.com/5601589/169685744-7da44736-da58-4231-ac48-9ae81e8f0d41.png)

Last one. Added to the list.

**Comment by seiyria** [comment]
please allow me to get help addressing: 2.5.5, suggestions.2, suggestions.4

(if this comment is older than 2 weeks, disregard this)

**Comment by kevinunger** [comment]
@seiyria 
- Created an issue with desc. for 2.5.5:  https://github.com/CryptoBlades/cryptoblades/issues/1490
- Suggestion 2 was just an idea that I added. The idea was to remove the links/icons from the right hamburger menu that are already present in the top nav-bar.
If everyone aggress with that, we can just remove the router-links in components/Options.vue that are already in components/ViewLinks.vue
- Suggestion 4 was resolved with the new game ui
- added your suggestion + issue https://github.com/CryptoBlades/cryptoblades/issues/1489

**Comment by remocwenn** [comment]
Anything that is not yet resolved, but is still needing to be resolved needs to be put into their own issues.
